In [1]:
from numpy import dot
from numpy.linalg import norm
import numpy as np
import pandas as pd
from konlpy.tag import Hannanum
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import numpy as np

In [2]:
hannanum = Hannanum()

In [3]:
df_stat = pd.read_excel('dongduk_course_statistic.xlsx')
df_stat['학수번호'] = df_stat['학수번호'].str.strip() #학수번호 공백없애기 
df_stat = df_stat[['학수번호','과목소개']] 
df_stat.head()

       학수번호                                               과목소개
0  데이 K0040      인터넷프로그래밍 (Internet Programming)  가.   네트워크...
1  데이 K0047      선형모형입문 (Introduction to Linear Models)  가....
2  데이 K0056      정보시스템 보안 및 관리 (Information System Security...
3  데이 K0045      정보시스템활용 (Application of Information System...
4  데이 K0052      생명과학자료분석 (Data Analysis for the Life Scien...

In [4]:
df_health = pd.read_excel('health.xlsx')
df_health['학수번호'] = df_health['학수번호'].str.strip() #학수번호 공백없애기 
df_health = df_health[['학수번호','과목소개']] 
df_health.head()

      학수번호                                               과목소개
0  보건B0005     보건교육학  보건교육학 Health Education 보건B 자료  보건교육 ...
1  보건K0025     의무기록전사  의무기록전사 Medical Record and Transcrip...
2  보건B0006     보건의료자료분석론  보건의료자료분석론 Health Care Data Analy...
3  보건K0033     보건프로그램개발 및 평가  보건프로그램개발 및 평가 Health Program...
4  보건K0017     건강위해성평가  건강위해성 평가 Health Risk Assessment 보건...

In [5]:
df_manage = pd.read_excel('dongduk_course_manage.xlsx')
df_manage['학수번호'] = df_manage['학수번호'].str.strip() #학수번호 공백없애기 
df_manage = df_manage[['학수번호','과목소개']] 
df_manage.head()

      학수번호                                               과목소개
0  경영K0033      중급회계Ⅱ   기업에 대한 정보를 외부의 이해관계자들에게 생산 전달하는 재무...
1  경영B0001      경영학원론   경영학이론의 발전과정 경영학의 체계 현대기업의 주요 경영이론 ...
2  경영B0001      경영학원론   경영학이론의 발전과정 경영학의 체계 현대기업의 주요 경영이론 ...
3  경영K0037      서비스마케팅   산업화가 진전됨에 따라 산업구조도 제조업에서 서비스업 중심으...
4  경영K0009      광고론   광고이론을 체계적으로 이해시키며 타 마케팅관련 변수들과의 유기적 ...

In [6]:
df_stat = df_stat.append(df_manage)
df_stat = df_stat.reset_index(drop=True)
df_stat.tail()

       학수번호                                               과목소개
67  경영K0013      세법개론   본 과목은 기업의 경영과 개인의 일상생활에서 중요성이 증대되고 ...
68  경영K0034      고급재무회계   중급회계에서 다루지 않았던 재무회계의 특수 분야인 고급수준의...
69  경영K0003      조직행동론   조직 내에서의 인간행동에 대한 원인을 규명하여 조직의 효율성을...
70  경영K0019      세무회계   본 과목은 세무회계의 이론과 실무를 이해시키고 기업회계와 세법의...
71  경영K0017      경영정보시스템   조직운영 및 경영활동을 지원하는 경영정보시스템에 관련된 학...

In [7]:
df_stat = df_stat.append(df_health)
df_stat = df_stat.reset_index(drop=True)
df_stat.tail()

        학수번호                                               과목소개
100  보건K0005     의무기록관리학  의무기록관리학 Medical Record Management ...
101  보건K0010     의학용어  의학용어 Medical Terminology 보건 K 자료  모든 ...
102  보건K0044     생활습관병과 영양  성인병과 영양 Adult Diseases and Nutri...
103  보건K0011     보건행정학  보건행정학 Public Health Administration 보...
104  보건K0006     병리학 및 실습  병리학 및 실습 Pathology and Practice 보...

In [8]:
df_stat

         학수번호                                               과목소개
0    데이 K0040      인터넷프로그래밍 (Internet Programming)  가.   네트워크...
1    데이 K0047      선형모형입문 (Introduction to Linear Models)  가....
2    데이 K0056      정보시스템 보안 및 관리 (Information System Security...
3    데이 K0045      정보시스템활용 (Application of Information System...
4    데이 K0052      생명과학자료분석 (Data Analysis for the Life Scien...
..        ...                                                ...
100   보건K0005     의무기록관리학  의무기록관리학 Medical Record Management ...
101   보건K0010     의학용어  의학용어 Medical Terminology 보건 K 자료  모든 ...
102   보건K0044     생활습관병과 영양  성인병과 영양 Adult Diseases and Nutri...
103   보건K0011     보건행정학  보건행정학 Public Health Administration 보...
104   보건K0006     병리학 및 실습  병리학 및 실습 Pathology and Practice 보...

[105 rows x 2 columns]

In [9]:
df_stat.to_csv('manage+stat+health.csv',index=False)

In [10]:
docs = []
for i in df_stat['과목소개']:  
    docs.append(hannanum.nouns(i))
    
for i in range(len(docs)):
    docs[i] = ' '.join(docs[i])
df_stat['과목소개'] = pd.Series(docs)
df_stat.head()#token화

       학수번호                                               과목소개
0  데이 K0040  인터넷프로그래밍 네트워크 프로그래밍 필요 기법들 이해 클라이언트 서버 통신 프로그램...
1  데이 K0047  선형모형입문 선형모형 확장 선형모형 기본이론 실습 병행 학습 나 중회귀모형, 분산분...
2  데이 K0056  정보시스템 보안 관리 & 정보시스템 보안 중요성 관리 방법 학습 나 정보시스템 보안...
3  데이 K0045  정보시스템활용 정보시스템 활용 능력 나 정보시스템 활용 능력 향상 사례분석 세미나 ...
4  데이 K0052  생명과학자료분석 의학 유전자 등 생명과학자료 특성 이 관련 통계분석방법 학습 실제 ...

In [11]:
df_ncs = pd.read_excel('j_ncs.xlsx',encoding='cp949')
df_ncs.head()

         jobname                                         capability
0      3D 프린터 개발  시장 조사하기 법규 검토하기 기술방식 비교하기 기술방식 선정하기 원가 분석하기 개발...
1  3D 프린터용 제품 제작  시장동향 분석하기 수요조사하기 사업성 검토하기 기획ㅈ품 설정하기 디자인 결정하기 출...
2            CAM  작업계획 수립하기 공정 · 작업내용 계획하기 장비 · 인원 배분하기 도면 결정하기 ...
3          CO2용접  용접작업 안전수칙 파악하기 용접작업장 주변 정리 상태 점검하기 용접 안전보호구 점검...
4        DB엔지니어링  데이터 요구사항 수집하기 데이터 요구사항 분석하기 데이터 요구사항 정의하기 데이터 ...

In [12]:
df_ncs.shape

(894, 2)

In [13]:
def cos_sim(A, B):
       return dot(A, B)/(norm(A)*norm(B))

In [14]:
df_ncs_original =  pd.read_excel('ncs_original.xlsx',encoding='cp949')
df_ncs_original.head()
df_ncs_original = df_ncs_original[['세분류','능력단위요소']]
df_ncs_original.columns = ['jobname','capability']
df_ncs_original.head()

       jobname       capability
0  공적개발원조 사업관리  협력대상국 개발환경 분석하기
1  공적개발원조 사업관리      자국협력환경 분석하기
2  공적개발원조 사업관리  협력대상국 지원전략 수립하기
3  공적개발원조 사업관리  협력대상국 개발전략 분석하기
4  공적개발원조 사업관리       사업타당성 조사하기

# cv추천

In [15]:
def cos_sim(A, B):
       return dot(A, B)/(norm(A)*norm(B))
    
courses_contents = [] 
def append_courses(df_name): #과목df이름을 매개변수로 
    courses = input('들은 과목들의 학수번호:').split(',')
    return     df_name[df_name['학수번호'].isin(courses)]['과목소개'].sum()

    
def cv_recommend_ten_job():
    cv = CountVectorizer()
    distance = []
    courses = append_courses(df_stat)
    for k in range(0,df_ncs.shape[0]):
        X = np.array(cv.fit_transform([courses, df_ncs.iloc[k,1]]).todense())
        distance.append(cos_sim(X[0], X[1]))
    df = pd.DataFrame(distance, index=df_ncs['jobname'],columns=['recommended job'])
    df = df.sort_values(by=['recommended job'], axis=0,ascending=False)
    return df[:10]

def recommened_job_more():
    df = cv_recommend_ten_job()
    print(df)
    df.reset_index(inplace=True)
    return pd.DataFrame(pd.merge(df, df_ncs_original,how='inner',on='jobname'))

    
def main():
    df = recommened_job_more()
    jobname = input('궁금한 직무를 입력 : ')
    return pd.DataFrame(df[df['jobname'] == jobname]['capability'])

In [23]:
main()

들은 과목들의 학수번호:데이 K0014,데이 K0058,경영B0005
                  recommended job
jobname
DB엔지니어링                  0.129197
제품디자인                    0.117573
출판기획                     0.112235
정보시스템운영                  0.107808
스마트문화앱콘텐츠제작              0.100778
IT마케팅                    0.100605
가상훈련구동엔지니어링              0.100383
이러닝시스템개발                 0.097003
스마트문화앱콘텐츠 유통·서비스         0.085339
통신판매                     0.078583
궁금한 직무를 입력 : DB엔지니어링

                                capability
0                            데이터 요구사항 수집하기
1                            데이터 요구사항 분석하기
2                            데이터 요구사항 정의하기
3                            데이터 요구사항 검증하기
4                                주제영역 정의하기
5                                핵심개체 정의하기
6                                핵심관계 정의하기
7                        개념 E-R 다이어그램 작성하기
8                          개념 데이터모델 품질검증하기
9                                 개체 상세화하기
10                                관계 상세화하기
11                       논리 E-R 다이어그램 작성하기
12                            데이터베이스 정규화하기
13                         논리 데이터모델 품질검증하기
14                            물리요소 조사 분석하기
15                        데이터베이스 물리속성 설계하기
16                       물리 E-R 다이어그램 작성하기
17                           데이터베이스 반정규화하기
18                         물리데이터 모델 품질검토하기
19  DBMS(Data Base Management System) 설치하기
20                             데이터베이스 생성하기
21                        데이터베이스 오브젝트 생성하기
22                           데이터 품질정책 수립하기
23                             데이터 품질 진단하기
24                             데이터 품질 개선하기
25                      데이터 품질관리 프로세스 정의하기
26                           데이터 전환계획 수립하기
27                             데이터 전환 설계하기
28                        데이터 전환 프로그램 구현하기
29                                데이터 정제하기
30                             데이터 전환 수행하기
31                                 성능 분석하기
32                                  성능개선하기
33                             성능개선결과 평가하기
34                          데이터 표준화 정책수립하기
35                             데이터 표준 정의하기
36                             데이터 표준 관리하기
37                             기본 SQL 작성하기
38                             고급 SQL 작성하기
39                            절차형 SQL 작성하기
40                             응용 SQL 작성하기

# tf-idf 추천

In [17]:
def cos_sim(A, B):
       return dot(A, B)/(norm(A)*norm(B))
    
courses_contents = [] 
def append_course(): 
    courses = input('들은 과목들의 학수번호:').split(',')
    for r in courses:
        index = df_stat.index[df_stat['학수번호'] == r ].tolist()  #학수번호 인덱스뽑기
        #print(index)
        k = df_stat[df_stat['학수번호'] == r ]['과목소개'][index[0]]  #과목소개 추출
        #print(k)
        courses_contents.append(k)  #course_contents리스트에 에펜드
        #print(courses_contents)
    return ''.join(courses_contents)

    
def tfidf_recommend_ten_job():
    cv = TfidfVectorizer()
    distance = []
    courses = append_courses(df_stat)
    #print(courses)
    for k in range(0,df_ncs.shape[0]):
        X = np.array(cv.fit_transform([courses, df_ncs.iloc[k,1]]).todense())
        distance.append(cos_sim(X[0], X[1]))
    df = pd.DataFrame(distance, index=df_ncs['jobname'],columns=['recommended job'])
    df = df.sort_values(by=['recommended job'], axis=0,ascending=False)
    return df[:10]

In [18]:
cv_recommend_ten_job()

들은 과목들의 학수번호:DB엔지니어

KeyboardInterrupt:

In [ ]:
tfidf_recommend_ten_job()

In [ ]:
database = tfidf_recommend_ten_job()

In [ ]:
database[:20]

In [ ]:
database.loc['유무선통합서비스',0]

In [ ]:
database[database['jobname'] != 0]

# 유클리디안

In [ ]:
def euclidean_distance(x, y):   
    return np.sqrt(np.sum((x - y) ** 2))
courses_contents = [] 
def append_course(): 
    courses = input('들은 과목들의 학수번호 (쉼표 기준):').split(',')
    for r in courses:
        index = df_stat.index[df_stat['학수번호'] == r ].tolist()  #학수번호 인덱스뽑기
        #print(index)
        k = df_stat[df_stat['학수번호'] == r ]['과목소개'][index[0]]  #과목소개 추출
        #print(k)
        courses_contents.append(k)  #course_contents리스트에 에펜드
        #print(courses_contents)
    return ''.join(courses_contents)

    
def u_tfidf_recommend_ten_job():
    cv = TfidfVectorizer()
    distance = []
    courses = append_courses(df_stat)
    #print(courses)
    for k in range(0,df_ncs.shape[0]):
        X = np.array(cv.fit_transform([courses, df_ncs.iloc[k,1]]).todense())
        distance.append(euclidean_distance(X[0], X[1]))
    df = pd.DataFrame(distance, index=df_ncs['jobname'],columns=['recommended job'])
    df = df.sort_values(by=['recommended job'], axis=0,ascending=False)
    return df

In [ ]:
u_tfidf_recommend_ten_job()